# -*- coding: utf-8 -*-
"""twitter sentiment analysis using ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUTf-MmXeOQ2E5AhhvVwWdI1uuB3yNdt
"""

# installing kaggle library
! pip install kaggle

"""# upload kaggle .json file"""

# configuring the path of kaggle.json file
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

"""# importing twitter sentiment dataset"""

# API to fetch the dataset from kaggle
!kaggle datasets download -d kazanova/sentiment140

# extrecting the compressed  dataset

from zipfile import ZipFile
dataset = '/content/sentiment140.zip'

with ZipFile(dataset, 'r') as zip:
  zip.extractall()
  print(' The dataset is extracted')

"""# importing the dependencies"""

import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import nltk
nltk.download('stopwords')

# printing the stopwords in english
print (stopwords.words('english'))

"""# data processing"""

# loading the data from csv file to pandas dataframe
twitter_data = pd.read_csv('/content/training.1600000.processed.noemoticon.csv', encoding= 'ISO-8859-1')

# CHECKING THE NO. OF rows and columns
twitter_data.shape

# printing the first 5 rows of the dataframe
twitter_data.head()

# naming the  colums and reading the dataset again

column_names = ['target','id','date','flag','user','text']
twitter_data = pd.read_csv('/content/training.1600000.processed.noemoticon.csv', names=column_names, encoding= 'ISO-8859-1')

# CHECKING THE NO. OF rows and columns
twitter_data.shape

# printing the first 5 rows of dataframe
twitter_data.head()

# counting the no. of missing values in the dataset
twitter_data.isnull().sum()

# checking the distribution of target column
twitter_data['target'].value_counts()

"""# convert the target "4" to "1"
"""

twitter_data.replace({'target':{4:1}}, inplace=True)

# checking the distribution of target column
twitter_data['target'].value_counts()

"""#0--------> Negative tweet
# 1--------> positive tweet

**Stemming**                                                     
steming is the process of reduceing a word to its roots word,    example -actor, actress, acting = act
"""

port_stem = PorterStemmer()

def stemming(content):

  stemmed_content = re.sub('[^a-zA-Z]','',content)
  stemmed_content = stemmed_content.lower()
  stemmed_content = stemmed_content.split()
  stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content = ''.join(stemmed_content)

  return stemmed_content

twitter_data['stemmed_content'] = twitter_data['text'].apply(stemming) # 50 minutes to complete thus execution

twitter_data.head()

print(twitter_data['stemmed_content'])

print(twitter_data['target'])

#seprating the data and label
X = twitter_data['stemmed_content'].values
Y = twitter_data['target'].values

print(X)

print(Y)

"""# Spliting the data into training data and test data set"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

print (X_train)

print (X_test)

# converting the textual data to numerical data

vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer. transform(X_test)

print (X_train)

print (X_test)

"""# training the machine learning model

**logestic regression**
"""

model = LogisticRegression(max_iter=1000)

model.fit(X_train, Y_train)

"""Model evaluation

**Accuracy score**
"""

# accuracy score on the training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)

print ('accuracy score on the training data: ', training_data_accuracy)

# accuracy score on the test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)

print ('accuracy score on the training data: ', test_data_accuracy)

"""# moder accuracy =  **0.512653125**

# Saving the trained model
"""

import pickle

filename = 'trained_model.sav'
pickle.dump(model, open(filename,'wb'))

"""# using the saved model for future prediction"""

# loading the savedmodel
loaded_model = pickle.load(open('/content/trained_model.sav','rb'))

x_new = X_test[200]
print(Y_test[200])

prediction = model.predict(X_test)
print(prediction)

if (prediction[0] == 0) :
  print('Negative tweet')

else:
     print('positive tweet')

x_new = X_test[528]
print(Y_test[528])

prediction = model.predict(X_test)
print(prediction)

if (prediction[0] == 0) :
  print('Negative tweet')

else:
     print('positive tweet')

